[build]
  base    = "deepwiki-ui"
  command = "npm run build -- --configuration=production"
  publish = "dist/deepwiki-ui/browser"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200